$script_mysql = <<-SCRIPT
useradd -m edgar_romani
apt-get update
apt-get install -y mysql-server-5.7
cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf
service mysql restart
cat /configs/chave.pub >> /home/vagrant/.ssh/authorized_keys

SCRIPT

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/bionic64"

    
    config.vm.define "host_mysql" do |mysql|
      mysql.vm.network "public_network", ip: "192.168.0.120"
      mysql.vm.synced_folder "./configs", "/configs"
      mysql.vm.synced_folder "./instaladores", "/instaladores"
      #Configs   
      #mysql.vm.provision "shell", inline: $script_mysql
      mysql.vm.provision "shell", inline: "cat /configs/chave.pub >> /home/vagrant/.ssh/authorized_keys"
      mysql.vm.provider  "virtualbox" do |vb|
        vb.name = "ubuntu_bionic_mysql"
      end
    end

    
    config.vm.define "host_php" do |php|
      php.vm.network "forwarded_port", guest: 7777, host: 7777
      php.vm.network "public_network", ip: "192.168.0.121"
      php.vm.provision "shell", inline: "apt-get update && apt-get install -y puppet"
      php.vm.provider  "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
        vb.name = "ubuntu_bionic_php"
      end
      php.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "./configs/manifests"
        puppet.manifest_file = "phpweb.pp"
      end
    end


    config.vm.define "host_ansible" do |ansible|
      ansible.vm.network "public_network", ip: "192.168.0.122"  
      ansible.vm.provider  "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus = 1
        vb.name = "ubuntu_bionic_ansible"
      end
      ansible.vm.provision "shell",
      inline: "apt-get update && \
               apt-get install -y software-properties-common && \
               apt-add-repository --yes --update ppa:ansible/ansible && \
               apt-get install -y ansible"
      ansible.vm.provision "shell", inline: "cp /vagrant/configs/chave /home/vagrant && \
      chmod 600 /home/vagrant/chave && \
      chown vagrant:vagrant /home/vagrant/chave"
    end


    config.vm.define "host_docker" do |hostdocker|
      hostdocker.vm.network "public_network", ip: "192.168.0.123" 
      hostdocker.vm.provision "shell", inline: "apt-get update && apt-get install -y docker.io"      
      config.vm.provider  "virtualbox" do |vb|
          vb.memory = 1024
          vb.cpus = 2
          vb.name = "host_docker"
    end
  end
end